### ISSUE TITLE
Course Statistics: Remove Show population button from Attemps-table view

### ISSUE THREAD

**Issue by anterogradinen** [UniversityOfHelsinkiCS/oodikone#3386] opened 2022-01-20 08:43 UTC
![image](https://user-images.githubusercontent.com/72501421/150303630-1d10fde7-3095-4538-b8bf-0ede2c3a62f4.png)

**Comment by anterogradinen** [comment] 2022-01-20 08:44
ks myös 
#3385
#3384 
#3383

**Comment by SNurmivaara** [comment] 2022-05-16 10:50
After some discussion decided on wontfix, as the view and "Show population" -button are working exactly as intended.

Some users have had questions why students and attempts aren't 1-to-1, but with some careful consideration on the nature of an attempt, i.e. that a student can have multiple attempts and this is the underlying reason we have these two views, no changes are required for now.

The view also has a "help" button that clarifies this as a tooltip. If users aren't finding it, some UI betterments could be considered in the future.

**Closed by SNurmivaara** 2022-05-16 10:50 UTC
