### ISSUE TITLE
[faculty basic tab] Credits do not (always) match

### ISSUE THREAD

**Issue by outisa** [UniversityOfHelsinkiCS/oodikone#4156] opened 2023-03-09 14:18 UTC
- [ ] Credit counts for TKT are changing by every refresh (If the data is not taken from redis)
- [ ] Are transferred students always sorted into correct 'boxes'?

**Comment by ShootingStar91** [comment] 2024-01-30 10:49
Couldn't reproduce the changing numbers issues. It is probably fixed at some point.

Transferred students is a separate issue, the number categories are looked at in a different issue, I will mention it there.

**Closed by ShootingStar91** 2024-01-30 10:49 UTC
Labels: bug, back, palkkausperuste, quality of life
