### ISSUE TITLE
custom population: make it possible to associate with a studyright

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3212] opened 2021-09-16 06:58 UTC
selection in creation form

**Comment by anterogradinen** [comment] 2021-09-16 07:00
![image](https://user-images.githubusercontent.com/72501421/133565181-58b66f76-cb34-41fc-9363-4a115032ab40.png)

**Comment by otahontas** [comment] 2022-01-10 12:40
Closing as duplicate of #3312

**Closed by otahontas** 2022-01-10 12:40 UTC
