### ISSUE TITLE
Updater writer is exploding

### ISSUE THREAD

**Issue by woltsu** [UniversityOfHelsinkiCS/oodikone#1158] opened 2019-07-24 06:53 UTC
READ COMMENTS!

![Screenshot 2019-07-24 at 9 48 13](https://user-images.githubusercontent.com/22446801/61771504-b0ba3a00-adf8-11e9-9375-1d185df41ef0.png)
![Screenshot 2019-07-24 at 9 49 03](https://user-images.githubusercontent.com/22446801/61771505-b0ba3a00-adf8-11e9-83a0-4cf9dc20f7f8.png)
![Screenshot 2019-07-24 at 9 52 52](https://user-images.githubusercontent.com/22446801/61771572-d5aead00-adf8-11e9-88a2-3230226d2edd.png)

**Comment by Rochet2** [comment] 2019-07-24 21:12
According to [google group](https://groups.google.com/forum/#!topic/natsio/o19jEY2JQiU) the situation is fixed once the timeouts in nats fire. However we can [configure our services to close nats](https://medium.com/@gchudnov/trapping-signals-in-docker-containers-7a57fdda7d86#.6b04xvnr8) when docker container closes and we can set the timeouts be smaller for nats to detect dead containers.
![image](https://user-images.githubusercontent.com/468816/61827981-5f4c9200-ae6e-11e9-8c8c-167481f28cfa.png)

For now it seems that deadlocks cannot be solved completely without locking the whole table for the duration of an operation OR without for example sorting all of our data so that rows within same table cannot be locked in different orders. We could maybe try retry the student immediately.
http://shiroyasha.io/deadlocks-in-postgresql.html
https://www.reddit.com/r/javascript/comments/9d2q72/sequelize_transactions_tips_on_avoiding_deadlock/

For SequelizeConnectionAcquireTimeoutError error it seems that sequelize had a bug in 5.x which should now be fixed, so just need to update sequelize. Our current one is 5.8.5.

**Comment by Rochet2** [comment] 2019-07-25 16:22
As can be seen from the log below, the updater writers sometimes suddenly start multiple messages even though nats is configured to only process a single message at a time.

```
updater_writer_1     | 2019-07-25T16:17:51.170898884Z starting 014716173
updater_writer_5     | 2019-07-25T16:17:51.751942881Z 014720619: 2759.244ms
updater_writer_5     | 2019-07-25T16:17:51.759055944Z starting 014621310
updater_writer_2     | 2019-07-25T16:17:53.662452619Z 013038768: 5429.205ms
updater_writer_2     | 2019-07-25T16:17:53.683829290Z starting 014446508
updater_writer_1     | 2019-07-25T16:17:54.248946275Z 014716173: 3077.951ms
updater_writer_1     | 2019-07-25T16:17:54.261619296Z starting 014722507
updater_writer_5     | 2019-07-25T16:17:54.665748494Z 014621310: 2906.523ms
updater_writer_5     | 2019-07-25T16:17:54.669985571Z starting 013826682
updater_writer_4     | 2019-07-25T16:17:55.823961485Z 014455230: 5654.933ms
updater_writer_4     | 2019-07-25T16:17:55.831152448Z starting 014718472
updater_writer_5     | 2019-07-25T16:17:56.103210499Z 013826682: 1433.070ms
updater_writer_5     | 2019-07-25T16:17:56.109676179Z starting 014809080
updater_writer_1     | 2019-07-25T16:17:56.886240323Z 014722507: 2624.328ms
updater_writer_1     | 2019-07-25T16:17:56.894728099Z starting 014997756
updater_writer_4     | 2019-07-25T16:17:57.258740978Z 014718472: 1427.465ms
updater_writer_4     | 2019-07-25T16:17:57.265194773Z starting 014721964
updater_writer_3     | 2019-07-25T16:17:57.440137803Z 014987818: 6578.258ms
updater_writer_3     | 2019-07-25T16:17:57.444456899Z starting 014923403
updater_writer_1     | 2019-07-25T16:17:57.675485566Z 014997756: 780.618ms
updater_writer_1     | 2019-07-25T16:17:57.681701340Z starting 011026248
updater_writer_2     | 2019-07-25T16:17:58.389189111Z 014446508: 4705.370ms
updater_writer_2     | 2019-07-25T16:17:58.396959460Z starting 014324086
updater_writer_4     | 2019-07-25T16:17:59.283489502Z 014721964: 2018.014ms
updater_writer_4     | 2019-07-25T16:17:59.326178684Z starting 013128458
updater_writer_3     | 2019-07-25T16:17:59.488178331Z 014923403: 2043.548ms
updater_writer_3     | 2019-07-25T16:17:59.490909640Z starting 014708343
updater_writer_2     | 2019-07-25T16:18:00.163523552Z starting 014710425
updater_writer_1     | 2019-07-25T16:18:00.196739808Z starting 011038919
updater_writer_5     | 2019-07-25T16:18:00.224312566Z starting 014470752
updater_writer_1     | 2019-07-25T16:18:00.244667890Z starting 010941421
updater_writer_2     | 2019-07-25T16:18:00.266255542Z starting 014588291
updater_writer_3     | 2019-07-25T16:18:00.272301347Z starting 014340691
updater_writer_5     | 2019-07-25T16:18:00.276430111Z starting 014696662
updater_writer_5     | 2019-07-25T16:18:00.287629560Z starting 014486872
updater_writer_5     | 2019-07-25T16:18:00.288668697Z starting 014939060
updater_writer_1     | 2019-07-25T16:18:00.292477235Z starting 014325742
updater_writer_3     | 2019-07-25T16:18:00.292686289Z starting 014141641
updater_writer_4     | 2019-07-25T16:18:00.321387054Z starting 014146808
updater_writer_3     | 2019-07-25T16:18:00.330356554Z starting 014937279
updater_writer_1     | 2019-07-25T16:18:00.340923774Z starting 013741563
updater_writer_2     | 2019-07-25T16:18:00.344757253Z starting 014809831
updater_writer_2     | 2019-07-25T16:18:00.350632324Z starting 014020542
updater_writer_4     | 2019-07-25T16:18:00.353727242Z starting 014484285
updater_writer_4     | 2019-07-25T16:18:00.354160830Z starting 014406069
updater_writer_3     | 2019-07-25T16:18:00.374879699Z starting 013763143
updater_writer_5     | 2019-07-25T16:18:00.539845992Z 014809080: 4430.012ms
updater_writer_5     | 2019-07-25T16:18:00.541159725Z starting 014049138
updater_writer_3     | 2019-07-25T16:18:00.569543196Z 014708343: 1078.459ms
updater_writer_3     | 2019-07-25T16:18:00.580133346Z starting 014333682
updater_writer_4     | 2019-07-25T16:18:00.849986630Z starting 014458130
updater_writer_2     | 2019-07-25T16:18:01.574222600Z 014324086: 3176.702ms
updater_writer_2     | 2019-07-25T16:18:01.577577421Z starting 014055274
updater_writer_1     | 2019-07-25T16:18:01.692750946Z 011026248: 4010.600ms
updater_writer_1     | 2019-07-25T16:18:01.696824259Z starting 010967544

```

When this error occurs, after a moment the writers start to spew out sequelize errors:
```
updater_writer_4     | 2019-07-25T16:19:00.171431777Z update failed 014482669 { SequelizeConnectionAcquireTimeoutError: Operation timeout
updater_writer_4     | 2019-07-25T16:19:00.171952318Z     at pool.acquire.catch.error (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
updater_writer_4     | 2019-07-25T16:19:00.172145855Z   name: 'SequelizeConnectionAcquireTimeoutError',
updater_writer_4     | 2019-07-25T16:19:00.172205442Z   parent:
updater_writer_4     | 2019-07-25T16:19:00.172330826Z    Error: Operation timeout
updater_writer_4     | 2019-07-25T16:19:00.172381366Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_4     | 2019-07-25T16:19:00.172585576Z        at ontimeout (timers.js:436:11)
updater_writer_4     | 2019-07-25T16:19:00.172640006Z        at tryOnTimeout (timers.js:300:5)
updater_writer_4     | 2019-07-25T16:19:00.172741877Z        at listOnTimeout (timers.js:263:5)
updater_writer_4     | 2019-07-25T16:19:00.172835067Z        at Timer.processTimers (timers.js:223:10),
updater_writer_4     | 2019-07-25T16:19:00.173257188Z   original:
updater_writer_4     | 2019-07-25T16:19:00.173413805Z    Error: Operation timeout
updater_writer_4     | 2019-07-25T16:19:00.173577952Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_4     | 2019-07-25T16:19:00.173955110Z        at ontimeout (timers.js:436:11)
updater_writer_4     | 2019-07-25T16:19:00.174141137Z        at tryOnTimeout (timers.js:300:5)
updater_writer_4     | 2019-07-25T16:19:00.174271067Z        at listOnTimeout (timers.js:263:5)
updater_writer_4     | 2019-07-25T16:19:00.174329341Z        at Timer.processTimers (timers.js:223:10) }
updater_writer_4     | 2019-07-25T16:19:00.175218759Z republishing UpdateWrite
updater_writer_2     | 2019-07-25T16:19:00.177224571Z update failed 014710425 { SequelizeConnectionAcquireTimeoutError: Operation timeout
updater_writer_2     | 2019-07-25T16:19:00.177281238Z     at pool.acquire.catch.error (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
updater_writer_2     | 2019-07-25T16:19:00.177300895Z   name: 'SequelizeConnectionAcquireTimeoutError',
updater_writer_2     | 2019-07-25T16:19:00.177314175Z   parent:
updater_writer_2     | 2019-07-25T16:19:00.177326021Z    Error: Operation timeout
updater_writer_2     | 2019-07-25T16:19:00.177356361Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_2     | 2019-07-25T16:19:00.177370245Z        at ontimeout (timers.js:436:11)
updater_writer_2     | 2019-07-25T16:19:00.177381968Z        at tryOnTimeout (timers.js:300:5)
updater_writer_2     | 2019-07-25T16:19:00.177392998Z        at listOnTimeout (timers.js:263:5)
updater_writer_2     | 2019-07-25T16:19:00.177404298Z        at Timer.processTimers (timers.js:223:10),
updater_writer_2     | 2019-07-25T16:19:00.177415181Z   original:
updater_writer_2     | 2019-07-25T16:19:00.177426055Z    Error: Operation timeout
updater_writer_2     | 2019-07-25T16:19:00.177437058Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_2     | 2019-07-25T16:19:00.177448758Z        at ontimeout (timers.js:436:11)
updater_writer_2     | 2019-07-25T16:19:00.177495182Z        at tryOnTimeout (timers.js:300:5)
updater_writer_2     | 2019-07-25T16:19:00.177513418Z        at listOnTimeout (timers.js:263:5)
updater_writer_2     | 2019-07-25T16:19:00.177525098Z        at Timer.processTimers (timers.js:223:10) }
updater_writer_2     | 2019-07-25T16:19:00.177536122Z republishing UpdateWrite
updater_writer_2     | 2019-07-25T16:19:00.181864148Z starting 014560727
updater_writer_4     | 2019-07-25T16:19:00.179882790Z update failed 010959138 { SequelizeConnectionAcquireTimeoutError: Operation timeout
updater_writer_4     | 2019-07-25T16:19:00.179998634Z     at pool.acquire.catch.error (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
updater_writer_4     | 2019-07-25T16:19:00.180020157Z   name: 'SequelizeConnectionAcquireTimeoutError',
updater_writer_4     | 2019-07-25T16:19:00.180033924Z   parent:
updater_writer_4     | 2019-07-25T16:19:00.180080534Z    Error: Operation timeout
updater_writer_4     | 2019-07-25T16:19:00.180121188Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_4     | 2019-07-25T16:19:00.180176591Z        at ontimeout (timers.js:436:11)
updater_writer_4     | 2019-07-25T16:19:00.180191298Z        at tryOnTimeout (timers.js:300:5)
updater_writer_4     | 2019-07-25T16:19:00.180203575Z        at listOnTimeout (timers.js:263:5)
updater_writer_4     | 2019-07-25T16:19:00.180245878Z        at Timer.processTimers (timers.js:223:10),
updater_writer_4     | 2019-07-25T16:19:00.180262698Z   original:
updater_writer_4     | 2019-07-25T16:19:00.180275078Z    Error: Operation timeout
updater_writer_4     | 2019-07-25T16:19:00.180300208Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_4     | 2019-07-25T16:19:00.180364172Z        at ontimeout (timers.js:436:11)
updater_writer_4     | 2019-07-25T16:19:00.180379388Z        at tryOnTimeout (timers.js:300:5)
updater_writer_1     | 2019-07-25T16:19:00.192197543Z update failed 014925508 { SequelizeConnectionAcquireTimeoutError: Operation timeout
updater_writer_1     | 2019-07-25T16:19:00.192263467Z     at pool.acquire.catch.error (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
updater_writer_4     | 2019-07-25T16:19:00.180390812Z        at listOnTimeout (timers.js:263:5)
updater_writer_4     | 2019-07-25T16:19:00.180433418Z        at Timer.processTimers (timers.js:223:10) }
updater_writer_4     | 2019-07-25T16:19:00.180447525Z republishing UpdateWrite
updater_writer_1     | 2019-07-25T16:19:00.192281227Z   name: 'SequelizeConnectionAcquireTimeoutError',
updater_writer_1     | 2019-07-25T16:19:00.192294560Z   parent:
updater_writer_1     | 2019-07-25T16:19:00.192307273Z    Error: Operation timeout
updater_writer_1     | 2019-07-25T16:19:00.192319660Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_1     | 2019-07-25T16:19:00.192332997Z        at ontimeout (timers.js:436:11)
updater_writer_1     | 2019-07-25T16:19:00.192345417Z        at tryOnTimeout (timers.js:300:5)
updater_writer_1     | 2019-07-25T16:19:00.192357484Z        at listOnTimeout (timers.js:263:5)
updater_writer_1     | 2019-07-25T16:19:00.192369667Z        at Timer.processTimers (timers.js:223:10),
updater_writer_1     | 2019-07-25T16:19:00.192381897Z   original:
updater_writer_1     | 2019-07-25T16:19:00.192393810Z    Error: Operation timeout
updater_writer_1     | 2019-07-25T16:19:00.192405854Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_1     | 2019-07-25T16:19:00.192437647Z        at ontimeout (timers.js:436:11)
updater_writer_1     | 2019-07-25T16:19:00.192450574Z        at tryOnTimeout (timers.js:300:5)
updater_writer_1     | 2019-07-25T16:19:00.192462384Z        at listOnTimeout (timers.js:263:5)
updater_writer_1     | 2019-07-25T16:19:00.192473394Z        at Timer.processTimers (timers.js:223:10) }
updater_writer_1     | 2019-07-25T16:19:00.192484807Z republishing UpdateWrite
updater_writer_2     | 2019-07-25T16:19:00.200159962Z update failed 014603600 { SequelizeConnectionAcquireTimeoutError: Operation timeout
updater_writer_2     | 2019-07-25T16:19:00.200242099Z     at pool.acquire.catch.error (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
updater_writer_2     | 2019-07-25T16:19:00.200263979Z   name: 'SequelizeConnectionAcquireTimeoutError',
updater_writer_2     | 2019-07-25T16:19:00.200276956Z   parent:
updater_writer_2     | 2019-07-25T16:19:00.200288662Z    Error: Operation timeout
updater_writer_2     | 2019-07-25T16:19:00.200300709Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_2     | 2019-07-25T16:19:00.200312629Z        at ontimeout (timers.js:436:11)
updater_writer_2     | 2019-07-25T16:19:00.200324019Z        at tryOnTimeout (timers.js:300:5)
updater_writer_2     | 2019-07-25T16:19:00.200335266Z        at listOnTimeout (timers.js:263:5)
updater_writer_2     | 2019-07-25T16:19:00.200361306Z        at Timer.processTimers (timers.js:223:10),
updater_writer_2     | 2019-07-25T16:19:00.200374266Z   original:
updater_writer_2     | 2019-07-25T16:19:00.200385723Z    Error: Operation timeout
updater_writer_2     | 2019-07-25T16:19:00.200397286Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_2     | 2019-07-25T16:19:00.200409059Z        at ontimeout (timers.js:436:11)
updater_writer_2     | 2019-07-25T16:19:00.200419963Z        at tryOnTimeout (timers.js:300:5)
updater_writer_2     | 2019-07-25T16:19:00.200431330Z        at listOnTimeout (timers.js:263:5)
updater_writer_2     | 2019-07-25T16:19:00.200442973Z        at Timer.processTimers (timers.js:223:10) }
updater_writer_2     | 2019-07-25T16:19:00.200712137Z republishing UpdateWrite
updater_writer_1     | 2019-07-25T16:19:00.207667033Z update failed 011038919 { SequelizeConnectionAcquireTimeoutError: Operation timeout
updater_writer_1     | 2019-07-25T16:19:00.207730666Z     at pool.acquire.catch.error (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
updater_writer_1     | 2019-07-25T16:19:00.207748647Z   name: 'SequelizeConnectionAcquireTimeoutError',
updater_writer_1     | 2019-07-25T16:19:00.207760943Z   parent:
updater_writer_1     | 2019-07-25T16:19:00.207772600Z    Error: Operation timeout
updater_writer_1     | 2019-07-25T16:19:00.207784310Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_1     | 2019-07-25T16:19:00.207796627Z        at ontimeout (timers.js:436:11)
updater_writer_1     | 2019-07-25T16:19:00.207807960Z        at tryOnTimeout (timers.js:300:5)
updater_writer_1     | 2019-07-25T16:19:00.207818880Z        at listOnTimeout (timers.js:263:5)
updater_writer_1     | 2019-07-25T16:19:00.207835100Z        at Timer.processTimers (timers.js:223:10),
updater_writer_1     | 2019-07-25T16:19:00.207846587Z   original:
updater_writer_1     | 2019-07-25T16:19:00.207857320Z    Error: Operation timeout
updater_writer_1     | 2019-07-25T16:19:00.207868333Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_1     | 2019-07-25T16:19:00.207879983Z        at ontimeout (timers.js:436:11)
updater_writer_1     | 2019-07-25T16:19:00.207890907Z        at tryOnTimeout (timers.js:300:5)
updater_writer_1     | 2019-07-25T16:19:00.207993780Z        at listOnTimeout (timers.js:263:5)
updater_writer_1     | 2019-07-25T16:19:00.208006157Z        at Timer.processTimers (timers.js:223:10) }
updater_writer_1     | 2019-07-25T16:19:00.208339695Z republishing UpdateWrite
updater_writer_4     | 2019-07-25T16:19:00.191005500Z update failed 014926109 { SequelizeConnectionAcquireTimeoutError: Operation timeout
updater_writer_4     | 2019-07-25T16:19:00.191060764Z     at pool.acquire.catch.error (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
updater_writer_4     | 2019-07-25T16:19:00.191079484Z   name: 'SequelizeConnectionAcquireTimeoutError',
updater_writer_4     | 2019-07-25T16:19:00.191093031Z   parent:
updater_writer_4     | 2019-07-25T16:19:00.191104794Z    Error: Operation timeout
updater_writer_4     | 2019-07-25T16:19:00.191117051Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_4     | 2019-07-25T16:19:00.191130054Z        at ontimeout (timers.js:436:11)
updater_writer_4     | 2019-07-25T16:19:00.191141864Z        at tryOnTimeout (timers.js:300:5)
updater_writer_4     | 2019-07-25T16:19:00.191153761Z        at listOnTimeout (timers.js:263:5)
updater_writer_4     | 2019-07-25T16:19:00.191166061Z        at Timer.processTimers (timers.js:223:10),
updater_writer_4     | 2019-07-25T16:19:00.191177627Z   original:
updater_writer_4     | 2019-07-25T16:19:00.191188734Z    Error: Operation timeout
updater_writer_4     | 2019-07-25T16:19:00.191200114Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_4     | 2019-07-25T16:19:00.191211864Z        at ontimeout (timers.js:436:11)
updater_writer_4     | 2019-07-25T16:19:00.191223204Z        at tryOnTimeout (timers.js:300:5)
updater_writer_4     | 2019-07-25T16:19:00.191236008Z        at listOnTimeout (timers.js:263:5)
updater_writer_4     | 2019-07-25T16:19:00.191247478Z        at Timer.processTimers (timers.js:223:10) }
updater_writer_3     | 2019-07-25T16:19:00.223274964Z update failed 014049125 { SequelizeConnectionAcquireTimeoutError: Operation timeout
updater_writer_3     | 2019-07-25T16:19:00.223448247Z     at pool.acquire.catch.error (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
updater_writer_3     | 2019-07-25T16:19:00.223516021Z   name: 'SequelizeConnectionAcquireTimeoutError',
updater_writer_3     | 2019-07-25T16:19:00.223536031Z   parent:
updater_writer_3     | 2019-07-25T16:19:00.223549254Z    Error: Operation timeout
updater_writer_3     | 2019-07-25T16:19:00.223561954Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_3     | 2019-07-25T16:19:00.223575481Z        at ontimeout (timers.js:436:11)
updater_writer_3     | 2019-07-25T16:19:00.223587768Z        at tryOnTimeout (timers.js:300:5)
updater_writer_3     | 2019-07-25T16:19:00.223599908Z        at listOnTimeout (timers.js:263:5)
updater_writer_3     | 2019-07-25T16:19:00.223645684Z        at Timer.processTimers (timers.js:223:10),
updater_writer_3     | 2019-07-25T16:19:00.223663774Z   original:
updater_writer_3     | 2019-07-25T16:19:00.223676114Z    Error: Operation timeout
updater_writer_3     | 2019-07-25T16:19:00.223688294Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_3     | 2019-07-25T16:19:00.223701525Z        at ontimeout (timers.js:436:11)
updater_writer_3     | 2019-07-25T16:19:00.223713521Z        at tryOnTimeout (timers.js:300:5)
updater_writer_3     | 2019-07-25T16:19:00.223725688Z        at listOnTimeout (timers.js:263:5)
updater_writer_5     | 2019-07-25T16:19:00.215460452Z update failed 014463976 { SequelizeConnectionAcquireTimeoutError: Operation timeout
updater_writer_5     | 2019-07-25T16:19:00.215635282Z     at pool.acquire.catch.error (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
updater_writer_4     | 2019-07-25T16:19:00.191259488Z republishing UpdateWrite
updater_writer_4     | 2019-07-25T16:19:00.220699621Z update failed 013201074 { SequelizeConnectionAcquireTimeoutError: Operation timeout
updater_writer_4     | 2019-07-25T16:19:00.220756794Z     at pool.acquire.catch.error (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
updater_writer_4     | 2019-07-25T16:19:00.220773308Z   name: 'SequelizeConnectionAcquireTimeoutError',
updater_writer_4     | 2019-07-25T16:19:00.220785361Z   parent:
updater_writer_4     | 2019-07-25T16:19:00.220796961Z    Error: Operation timeout
updater_writer_4     | 2019-07-25T16:19:00.220808218Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_4     | 2019-07-25T16:19:00.220820428Z        at ontimeout (timers.js:436:11)
updater_writer_4     | 2019-07-25T16:19:00.220832171Z        at tryOnTimeout (timers.js:300:5)
updater_writer_4     | 2019-07-25T16:19:00.220843624Z        at listOnTimeout (timers.js:263:5)
updater_writer_4     | 2019-07-25T16:19:00.220854971Z        at Timer.processTimers (timers.js:223:10),
updater_writer_4     | 2019-07-25T16:19:00.220889918Z   original:
updater_writer_4     | 2019-07-25T16:19:00.220902825Z    Error: Operation timeout
updater_writer_4     | 2019-07-25T16:19:00.220914255Z        at Timeout._timeout.setTimeout (/usr/src/app/node_modules/sequelize-pool/lib/Deferred.js:19:19)
updater_writer_4     | 2019-07-25T16:19:00.220936651Z        at ontimeout (timers.js:436:11)
```

**Comment by Rochet2** [comment] 2019-07-31 07:37
Possibly fixed:
It seems that after ensuring that we always ack every message everything rolls smoothly (at least so far). So even if there are errors we ack. NATS might have some issue with handling messages that never ack. Ack wait timeout is not helping. Even if the timeout ran out no new messages arrived. Acking always seems to fix random freeze in the flow of nats messages (nats never recovered from freeze).

Deadlocks were fixed by sorting the inserted data by DB primary key for every inserted list of data to each table before adding it to transaction.

Sequelize was updated to latest version, which either completely solved or at least alleviated the problems with SequelizeConnectionAcquireTimeoutError. In last update run there were no errors with DB (no deadlock or acquire timeout etc).

Remaining issues:
Sometimes multiple messages are popped from nats to be handled at the same time even if limited to 1 message at a time. Unsure if caused by scaling docker containers, timing out (nack) or some other issue. We can possibly just try increase ack wait time.

**Closed** 2019-08-06 16:55 UTC
Labels: bug
